// Generated by CoffeeScript 1.12.7
(function() {
  var $, App, Expression, Results, TestStrings,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = jQuery;

  Expression = (function(superClass) {
    extend(Expression, superClass);

    function Expression() {
      return Expression.__super__.constructor.apply(this, arguments);
    }

    Expression.prototype.elements = {
      'input[name=expression]': 'regexp',
      'input[name=option]': 'option'
    };

    Expression.prototype.events = {
      'keyup input': 'onKeyPress'
    };

    Expression.prototype.onKeyPress = function(event) {
      var error;
      try {
        this.value = this.buildRegex(this.regexp.val(), this.option.val());
      } catch (error1) {
        error = error1;
      }
      return this.trigger('update');
    };

    Expression.prototype.buildRegex = function(value, option) {
      return new RegExp(value, option);
    };

    Expression.prototype.asUrlPart = function() {
      return encodeURIComponent(this.regexp.val() + "||||" + this.option.val());
    };

    return Expression;

  })(Spine.Controller);

  TestStrings = (function(superClass) {
    extend(TestStrings, superClass);

    function TestStrings() {
      return TestStrings.__super__.constructor.apply(this, arguments);
    }

    TestStrings.prototype.elements = {
      'textarea': 'input'
    };

    TestStrings.prototype.events = {
      'keyup textarea': 'onKeyPress'
    };

    TestStrings.prototype.onKeyPress = function(event) {
      this.getValues(this.input.val());
      return this.trigger('update');
    };

    TestStrings.prototype.getValues = function(val) {
      return this.values = val.split('\n');
    };

    TestStrings.prototype.asUrlPart = function() {
      return encodeURIComponent(JSON.stringify(this.values));
    };

    return TestStrings;

  })(Spine.Controller);

  Results = (function() {
    function Results(expression, test_strings1) {
      this.expression = expression;
      this.test_strings = test_strings1;
      this.compile = bind(this.compile, this);
      this.expression.bind('update', this.compile);
      this.test_strings.bind('update', this.compile);
    }

    Results.prototype.compile = function() {
      var count, error, i, len, matches, ref, value;
      $('ul#results').empty();
      $('ul#groups').empty();
      count = 1;
      if (this.expression.regexp.val() !== '') {
        try {
          new RegExp(this.expression.regexp.val());
        } catch (error1) {
          this.showRegexError();
          return true;
        }
      }
      if (this.expression.regexp.val() === '' && this.test_strings.input.val() === '') {
        this.showIntro();
        return true;
      } else if (this.expression.regexp.val() === '' || this.test_strings.input.val() === '') {
        this.showError();
        return true;
      } else if (!this.test_strings.values) {
        return true;
      }
      try {
        ref = this.test_strings.values;
        for (i = 0, len = ref.length; i < len; i++) {
          value = ref[i];
          matches = value.match(this.expression.value);
          this.matchResults(value, matches);
          this.matchGroups(value, matches, count);
          count += 1;
        }
        this.addShareLink(this.expression.asUrlPart(), this.test_strings.asUrlPart());
        return this.showOutput();
      } catch (error1) {
        error = error1;
        return this.showError();
      }
    };

    Results.prototype.addShareLink = function(expression_url, test_strings_url) {
      var url;
      url = window.location.protocol + "//" + window.location.host;
      url += "/#" + expression_url + encodeURIComponent("||||") + test_strings_url;
      return $("#share_link").attr("href", url);
    };


    /*
      escape function from Peter Hoffman found at
      http://peter-hoffmann.com/2012/coffeescript-string-interpolation-with-html-escaping.html
     */

    Results.prototype.escape = function(s) {
      return ('' + s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#x27;').replace(/\//g, '&#x2F;');
    };

    Results.prototype.matchResults = function(value, matches) {
      var string;
      if (!matches) {
        return;
      }
      string = this.generateMatches(value, this.expression.value);
      return this.drawResult(string);
    };

    Results.prototype.generateMatches = function(value, regex) {
      return this.escape(value.replace(regex, "~~scriptular_begin_match~~$&~~scriptular_end_match~~")).replace(/~~scriptular_begin_match~~/g, '<span>').replace(/~~scriptular_end_match~~/g, '</span>');
    };

    Results.prototype.drawResult = function(string) {
      return $('ul#results').append("<li>" + string + "</li>");
    };

    Results.prototype.matchGroups = function(value, matches, count) {
      var i, j, len, len1, match, ref;
      if (!matches) {
        return;
      }
      $('ul#groups').append("<li id='match_" + count + "'><h3>Match " + count + "</h3><ol></ol></li>");
      if (this.expression.value.global) {
        for (i = 0, len = matches.length; i < len; i++) {
          match = matches[i];
          if (match === '') {
            return;
          }
          this.drawGroup(count, match);
        }
      } else {
        ref = matches.slice(1);
        for (j = 0, len1 = ref.length; j < len1; j++) {
          match = ref[j];
          if (match === '') {
            return;
          }
          this.drawGroup(count, match);
        }
      }
    };

    Results.prototype.drawGroup = function(count, match) {
      match = this.escape(match);
      return $("ul#groups li#match_" + count + " ol").append("<li>" + match + "</li>");
    };

    Results.prototype.showIntro = function() {
      $('#error').hide();
      $('#output').hide();
      $('#intro').show();
      return $('#regex-error').hide();
    };

    Results.prototype.showError = function() {
      $('#intro').hide();
      $('#output').hide();
      $('#error').show();
      return $('#regex-error').hide();
    };

    Results.prototype.showOutput = function() {
      $('#intro').hide();
      $('#error').hide();
      $('#output').show();
      return $('#regex-error').hide();
    };

    Results.prototype.showRegexError = function() {
      $('#intro').hide();
      $('#error').hide();
      $('#output').hide();
      return $('#regex-error').show();
    };

    return Results;

  })();

  App = (function() {
    function App() {
      this.load = bind(this.load, this);
      this.loadExample = bind(this.loadExample, this);
      this.loadFromHash = bind(this.loadFromHash, this);
      this.expression = new Expression({
        el: '#expression'
      });
      this.test_strings = new TestStrings({
        el: '#test_strings'
      });
      this.results = new Results(this.expression, this.test_strings);
      $('#example').bind('click', this.loadExample);
      if (window.location.hash !== '') {
        this.loadFromHash();
      }
    }

    App.prototype.loadFromHash = function() {
      var option, ref, regex, test_strings_from_url;
      ref = decodeURIComponent(window.location.hash.substr(1)).split("||||"), regex = ref[0], option = ref[1], test_strings_from_url = ref[2];
      test_strings_from_url = JSON.parse(test_strings_from_url);
      return this.load(regex, option, test_strings_from_url);
    };

    App.prototype.loadExample = function(event) {
      var option, regex, test_strings;
      event.preventDefault();
      regex = "^(https?)://((?:[A-Z0-9]*\\\.?)*)((?:\\\/?[A-Z0-9])*)";
      option = 'i';
      test_strings = ['https://github.com/jonmagic/scriptular', 'http://scriptular.com', 'http://www.google.com', 'http://www.guardian.co.uk'];
      return this.load(regex, option, test_strings);
    };

    App.prototype.load = function(regex, option, test_strings) {
      $('input[name=expression]').val(regex);
      $('input[name=option]').val(option);
      $('textarea').val(test_strings.join('\n'));
      this.expression.onKeyPress();
      this.test_strings.onKeyPress();
      return this.results.compile;
    };

    return App;

  })();

  window.App = App;

  window.$ = $;

}).call(this);
